apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: "${{values.displayName}}"
  name: "${{values.name}}"
  description: "${{values.description}}"
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "${{values.owner}}"
